### ISSUE TITLE
Workflow Executions List page for a specific Template

### ISSUE THREAD

**Issue by aleksandrmelnikov** [onepanelio/core#232]
Create a workflow template, "aaa"
- Create a few workflow executions
Archive that workflow template
- Create a new workflow template, "aaa"
The workflow executions from the previous template will show up in the list.
- This happens if the delete process didn't work properly, so there are orphans

Screenshot examples follow
![image](https://user-images.githubusercontent.com/10407733/82591295-fa2c0080-9b53-11ea-9071-6b9ac05d99e0.png)

![image](https://user-images.githubusercontent.com/10407733/82591352-116aee00-9b54-11ea-855b-595d52ad5cb6.png)

![image](https://user-images.githubusercontent.com/10407733/82591371-1a5bbf80-9b54-11ea-82a0-602cf3805e6c.png)

Notice that the workflow executions are from template id 2, but template 2 is archived.
Template 11 is the current one.

**Comment by aleksandrmelnikov** [comment]
This should be fixed with https://github.com/onepanelio/core/pull/226
- The addition of "is_archived" fixes this issue, since archived executions are not returned.
Tested this on the image data above.

**Comment by rushtehrani** [comment]
Need to verify that this has been addressed with https://github.com/onepanelio/core/pull/248

**Comment by rushtehrani** [comment]
@aleksandrmelnikov this is still an issue with workflow executions that were not created by a cron workflow
