### ISSUE TITLE
Fail to create any workspace and workflow. （AKS）

### ISSUE THREAD

**Issue by xyc2690** [onepanelio/core#766]
**Describe the bug**
Fail to create any workspace and workflow.
Unschedulable: 0/2 nodes are available: 2 pod has unbound immediate PersistentVolumeClaims.

Could it be the problem of the yaml?
```
#################################################################
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Component: Database
# Description: Database connection information
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
database:
  # Name of database
  # If using an external production database, use the name of that database.
  # For in-cluster test database, use any name you like.
  databaseName: onepanel
  # Do not change, only `postgres` driver is supported at this time.
  driverName: postgres
  # Database host - use `postgres` for in-cluster test database
  host: postgres
  # Database password
  # If using an external production database, use the password for that database.
  # For in-cluster test database, use any password you like.
  password: onepanel
  # Database port
  port: 5432
  # Database username
  # If using an external production database, use the username for that database.
  # For in-cluster test database, use any username you like.
  username: onepaneldemo
##################################################################
```
**`opctl` version**
```bash
$ opctl version

CLI version: v0.15.0-rc.0
Manifest version: v0.15.0-rc.0
API version: v0.15.0-rc.0
Web UI version: v0.15.0-rc.0
```

**`opctl init` command**
opctl init --provider aks --artifact-repository-provider s3 --gpu-device-plugins nvidia

**Kubernetes information**
 - Cloud provider: AKS
 - Kubernetes version: 1.18.10

**Machine information**
- OS:  Windows 10 
- Browser: Chrome, Firefox

**Screenshots**

**Comment by rushtehrani** [comment]
Can you make sure your [nodePool configuration](https://docs.onepanel.ai/docs/deployment/configuration/files) is correct?

**Comment by xyc2690** [comment]
> 
> 
> Can you make sure your [nodePool configuration](https://docs.onepanel.ai/docs/deployment/configuration/files) is correct?

Yes, I followed all the steps, and I have tried with different node configurations, still not working.  

Here is my node info and configs:

```bash
kubectl get nodes --show-labels
NAME                                STATUS    AGE       VERSION    LABELS
aks-agentpool-38405028-vmss000000   Ready     20h       v1.18.10   agentpool=agentpool,beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=Standard_DS3_v2,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=eastus2,failure-domain.beta.kubernetes.io/zone=eastus2-1,kubernetes.azure.com/cluster=MC_devxyc_devxyc_eastus2,kubernetes.azure.com/mode=system,kubernetes.azure.com/node-image-version=AKSUbuntu-1804-2020.11.11,kubernetes.azure.com/role=agent,kubernetes.io/arch=amd64,kubernetes.io/hostname=aks-agentpool-38405028-vmss000000,kubernetes.io/os=linux,kubernetes.io/role=agent,node-role.kubernetes.io/agent=,node.kubernetes.io/instance-type=Standard_DS3_v2,storageprofile=managed,storagetier=Premium_LRS,topology.kubernetes.io/region=eastus2,topology.kubernetes.io/zone=eastus2-1
aks-agentpool-38405028-vmss000001   Ready     20h       v1.18.10   agentpool=agentpool,beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=Standard_DS3_v2,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=eastus2,failure-domain.beta.kubernetes.io/zone=eastus2-2,kubernetes.azure.com/cluster=MC_devxyc_devxyc_eastus2,kubernetes.azure.com/mode=system,kubernetes.azure.com/node-image-version=AKSUbuntu-1804-2020.11.11,kubernetes.azure.com/role=agent,kubernetes.io/arch=amd64,kubernetes.io/hostname=aks-agentpool-38405028-vmss000001,kubernetes.io/os=linux,kubernetes.io/role=agent,node-role.kubernetes.io/agent=,node.kubernetes.io/instance-type=Standard_DS3_v2,storageprofile=managed,storagetier=Premium_LRS,topology.kubernetes.io/region=eastus2,topology.kubernetes.io/zone=eastus2-2
```

```bash
  nodePool:
    label: beta.kubernetes.io/instance-type
    # Add more by following the format:
    # - name: <name>
    #   value: <value>
    # The first option will be used as default.
    options:
      - name: 'CPU: 4, RAM: 14GB'
        value: Standard_DS3_v2
        # resources:
        #   limits:
        #     nvidia.com/gpu:1
        #     cpu: 5000m
        #     memory 50000Mi
  # The kubernetes cluster where Onepanel will be deployed.
  # Valid values: minikube, microk8s, aks, eks, gke
  provider: aks
```

**Comment by rushtehrani** [comment]
Can you launch a Workspace and share the events logs?

```
kubectl describe pods <workspace-name>-0 -n <your-namespace>
```

**Comment by rushtehrani** [comment]
Also, I see you are using `0.16.0-rc.0` but your params.yaml has `resources` under `nodePool`.  Can you confirm that you initialized you ran the init command with the same version of `opctl`? If not, I suggest you run your `opctl init` command again with this version and try `opctly apply`

**Comment by xyc2690** [comment]
> Can you launch a Workspace and share the events logs?
> 
> ```
> kubectl describe pods <workspace-name>-0 -n <your-namespace>
> ```

```
E:\GKE>kubectl.exe describe po -n onepaneldemo name-0
Name:         name-0
Namespace:    onepaneldemo
Priority:     0
Node:         gke-oneone-default-pool-bbb5699b-lgft/10.142.0.3
Start Time:   Wed, 09 Dec 2020 14:38:00 +0800
Labels:       app=name
              controller-revision-hash=name-7dd87b6f44
              istio.io/rev=default
              security.istio.io/tlsMode=istio
              service.istio.io/canonical-name=name
              service.istio.io/canonical-revision=latest
              statefulset.kubernetes.io/pod-name=name-0
Annotations:  prometheus.io/path: /stats/prometheus
              prometheus.io/port: 15020
              prometheus.io/scrape: true
              sidecar.istio.io/status:
                {"version":"8e6e902b765af607513b28d284940ee1421e9a0d07698741693b2663c7161c11","initContainers":["istio-init"],"containers":["istio-proxy"]...
Status:       Pending
IP:           10.0.0.135
IPs:
  IP:           10.0.0.135
Controlled By:  StatefulSet/name
Init Containers:
  istio-init:
    Container ID:  docker://c430a61dcecae451069c2965a813ec38a2129f2652b9b591f4d5307a84da3291
    Image:         docker.io/istio/proxyv2:1.7.3
    Image ID:      docker-pullable://istio/proxyv2@sha256:6169d096fe60f128f1311f76c97ee1c3e5d760a45042d5c9182492745d34c658
    Port:          <none>
    Host Port:     <none>
    Args:
      istio-iptables
      -p
      15001
      -z
      15006
      -u
      1337
      -m
      REDIRECT
      -i
      *
      -x

      -b
      *
      -d
      15090,15021,15020
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Wed, 09 Dec 2020 14:38:17 +0800
      Finished:     Wed, 09 Dec 2020 14:38:18 +0800
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     2
      memory:  1Gi
    Requests:
      cpu:     10m
      memory:  10Mi
    Environment:
      DNS_AGENT:
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-c79np (ro)
Containers:
  istio-proxy:
    Container ID:
    Image:         docker.io/istio/proxyv2:1.7.3
    Image ID:
    Port:          15090/TCP
    Host Port:     0/TCP
    Args:
      proxy
      sidecar
      --domain
      $(POD_NAMESPACE).svc.cluster.local
      --serviceCluster
      name.$(POD_NAMESPACE)
      --proxyLogLevel=warning
      --proxyComponentLogLevel=misc:error
      --trust-domain=cluster.local
      --concurrency
      2
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     2
      memory:  1Gi
    Requests:
      cpu:      100m
      memory:   128Mi
    Readiness:  http-get http://:15021/healthz/ready delay=1s timeout=1s period=2s #success=1 #failure=30
    Environment:
      JWT_POLICY:                    third-party-jwt
      PILOT_CERT_PROVIDER:           istiod
      CA_ADDR:                       istiod.istio-system.svc:15012
      POD_NAME:                      name-0 (v1:metadata.name)
      POD_NAMESPACE:                 onepaneldemo (v1:metadata.namespace)
      INSTANCE_IP:                    (v1:status.podIP)
      SERVICE_ACCOUNT:                (v1:spec.serviceAccountName)
      HOST_IP:                        (v1:status.hostIP)
      CANONICAL_SERVICE:              (v1:metadata.labels['service.istio.io/canonical-name'])
      CANONICAL_REVISION:             (v1:metadata.labels['service.istio.io/canonical-revision'])
      PROXY_CONFIG:                  {"proxyMetadata":{"DNS_AGENT":""}}

      ISTIO_META_POD_PORTS:          [
                                         {"name":"node-capturer","hostPort":80,"containerPort":80,"protocol":"TCP"}
                                         ,{"name":"jupyterlab","containerPort":8888,"protocol":"TCP"}
                                         ,{"name":"tensorboard","containerPort":6006,"protocol":"TCP"}
                                     ]
      ISTIO_META_APP_CONTAINERS:     node-capturer,jupyterlab
      ISTIO_META_CLUSTER_ID:         Kubernetes
      ISTIO_META_INTERCEPTION_MODE:  REDIRECT
      ISTIO_META_WORKLOAD_NAME:      name
      ISTIO_META_OWNER:              kubernetes://apis/apps/v1/namespaces/onepaneldemo/statefulsets/name
      ISTIO_META_MESH_ID:            cluster.local
      DNS_AGENT:
      ISTIO_KUBE_APP_PROBERS:        {}
    Mounts:
      /etc/istio/pod from istio-podinfo (rw)
      /etc/istio/proxy from istio-envoy (rw)
      /var/lib/istio/data from istio-data (rw)
      /var/run/secrets/istio from istiod-ca-cert (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-c79np (ro)
      /var/run/secrets/tokens from istio-token (rw)
  node-capturer:
    Container ID:
    Image:         alpine:latest
    Image ID:
    Port:          80/TCP
    Host Port:     80/TCP
    Command:
      /bin/sh
    Args:
      -c
      while :; do sleep 2073600; done
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-c79np (ro)
  jupyterlab:
    Container ID:
    Image:         onepanel/jupyterlab:1.0.1
    Image ID:
    Ports:         8888/TCP, 6006/TCP
    Host Ports:    0/TCP, 0/TCP
    Command:
      /bin/bash
      -c
      pip install onepanel-sdk && start.sh jupyter lab --LabApp.token='' --LabApp.allow_remote_access=True --LabApp.allow_origin="*" --LabApp.disable_check_xsrf=True --LabApp.trust_xheaders=True --LabApp.base_url=/ --LabApp.tornado_settings='{"headers":{"Content-Security-Policy":"frame-ancestors * 'self'"}}' --notebook-dir='/data' --allow-root
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Environment Variables from:
      onepanel-default-env  Secret  Optional: true
    Environment:
      ONEPANEL_RESOURCE_UID:        name
      ONEPANEL_RESOURCE_NAMESPACE:  onepaneldemo
      ONEPANEL_PROVIDER:            gke
      ONEPANEL_DOMAIN:              xyc2690.xyz
      ONEPANEL_FQDN:                app.xyc2690.xyz
      ONEPANEL_API_URL:             http://app.xyc2690.xyz/api
      tornado:                      '{'headers':{'Content-Security-Policy':"frame-ancestors * 'self'"}}'
      TENSORBOARD_PROXY_URL:        //$(ONEPANEL_RESOURCE_UID)--$(ONEPANEL_RESOURCE_NAMESPACE).$(ONEPANEL_DOMAIN)/tensorboard
    Mounts:
      /data from data (rw)
      /dev/shm from sys-dshm (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-c79np (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  data-name-0
    ReadOnly:   false
  sys-dshm:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  <unset>
  sys-namespace-config:
    Type:                Projected (a volume that contains injected data from multiple sources)
    ConfigMapName:       onepanel
    ConfigMapOptional:   <nil>
    SecretName:          onepanel
    SecretOptionalName:  <nil>
  default-token-c79np:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-c79np
    Optional:    false
  istio-envoy:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  <unset>
  istio-data:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  istio-podinfo:
    Type:  DownwardAPI (a volume populated by information about the pod)
    Items:
      metadata.labels -> labels
      metadata.annotations -> annotations
  istio-token:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  43200
  istiod-ca-cert:
    Type:        ConfigMap (a volume populated by a ConfigMap)
    Name:        istio-ca-root-cert
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  beta.kubernetes.io/instance-type=n1-standard-8
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason                  Age                    From                     Message
  ----     ------                  ----                   ----                     -------
  Warning  FailedScheduling        2m54s (x2 over 2m54s)  default-scheduler        0/3 nodes are available: 3 pod has unbound immediate PersistentVolumeClaims.
  Normal   Scheduled               2m51s                  default-scheduler        Successfully assigned onepaneldemo/name-0 to gke-oneone-default-pool-bbb5699b-lgft
  Normal   SuccessfulAttachVolume  2m47s                  attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-d24fef91-585e-4609-a1e6-242e5fc31958"
  Normal   Started                 2m34s                  kubelet                  Started container istio-init
  Normal   Pulling                 2m34s                  kubelet                  Pulling image "docker.io/istio/proxyv2:1.7.3"
  Normal   Pulled                  2m34s                  kubelet                  Successfully pulled image "docker.io/istio/proxyv2:1.7.3"
  Normal   Created                 2m34s                  kubelet                  Created container istio-init
  Normal   Started                 2m33s                  kubelet                  Started container istio-proxy
  Normal   Pulling                 2m33s                  kubelet                  Pulling image "docker.io/istio/proxyv2:1.7.3"
  Normal   Created                 2m33s                  kubelet                  Created container istio-proxy
  Normal   Pulled                  2m33s                  kubelet                  Successfully pulled image "docker.io/istio/proxyv2:1.7.3"
  Normal   Pulling                 2m32s                  kubelet                  Pulling image "alpine:latest"
  Normal   Pulled                  2m31s                  kubelet                  Successfully pulled image "alpine:latest"
  Normal   Created                 2m31s                  kubelet                  Created container node-capturer
  Normal   Started                 2m31s                  kubelet                  Started container node-capturer
  Normal   Pulling                 2m31s                  kubelet                  Pulling image "onepanel/jupyterlab:1.0.1"
```

**Comment by xyc2690** [comment]
> Also, I see you are using `0.16.0-rc.0` but your params.yaml has `resources` (deprecated in 0.16.0) under `nodePool`. Can you confirm that you initialized you ran the init command with the same version of `opctl`? If not, I suggest you run your `opctl init` command again with this version and try `opctly apply`

I checked the opctl version. And I tried to use GKE, and came out the same error. 
```
E:\GKE>opctl-windows-amd64.exe version
CLI version: v0.15.0
Manifest version: v0.15.0
API version: v0.15.0
Web UI version: v0.15.0
```

**Comment by rushtehrani** [comment]
Your database settings are correct. If that was the issue, `onepanel-core` pod would also crash. Few questions/observations:
1. Are you using a real domain name or a setting the domain in a hosts file?
2. Does the pod Workspace pod actually run after a while or is what you sent the last event it gets stuck at?
3. Looks like you're using GKE 1.18.12, can you try using `node.kubernetes.io/instance-type` for the `nodePool` key in your params.yaml file? You can just make the change and run `opctl apply` again.

**Comment by xyc2690** [comment]
> Your database settings are correct. If that was the issue, `onepanel-core` pod would also crash. Few questions/observations:
> 
> 1. Are you using a real domain name or a setting the domain in a hosts file?
> 2. Does the pod Workspace pod actually run after a while or is what you sent the last event it gets stuck at?
> 3. Looks like you're using GKE 1.18.12, can you try using `node.kubernetes.io/instance-type` for the `nodePool` key in your params.yaml file? You can just make the change and run `opctl apply` again.

Thanks for your reply. 
1. I use a real domain name which is : app.xyc2690.xyz 
```
E:\GKE>opctl-windows-amd64.exe auth token
admin
22c3650f61866aa3f037a4ef280da7c8
```
2. The pod workspace pod actually run 'status: running'. However when you enter the workspace, there is nothing.
3. I Replaced the key and applied, still got the same problem.

**Comment by rushtehrani** [comment]
> 1. I use a real domain name which is : app.xyc2690.xyz

Ok, can you confirm that you set up your A record as: `*.app.xyc2690.xyz` in your DNS? It should be set like so (note the `*.`):
```
*.app                A                    <IP address>
```

**Comment by xyc2690** [comment]
> > 1. I use a real domain name which is : app.xyc2690.xyz
> 
> Ok, can you confirm that you set up your A record as: `*.xyc2690.xyz` in your DNS? It should be set like below (note the `*`):
> 
> ```
> *               A                    <IP address>
> ```

Yes, and I can login the page.
![dns](https://user-images.githubusercontent.com/13115224/101719283-fa82ed80-3add-11eb-99a0-7e542ac92165.png)

**Comment by rushtehrani** [comment]
You only need the `*` since that also covers `app`. Things should be working now, can you confirm? I pinged `test.xyc2690.xyz` and got a response, I was not able to before.

**Comment by xyc2690** [comment]
> You only need the `*` since that also covers `app`. Things should be working now, can you confirm? I pinged `test.xyc2690.xyz` and got a response, I was not able to before.

still can't create workspace

'''
Warning  FailedScheduling        2m54s (x2 over 2m54s)  default-scheduler        0/3 nodes are available: 3 pod has unbound immediate PersistentVolumeClaims.
'''

**Comment by xyc2690** [comment]
> You only need the `*` since that also covers `app`. Things should be working now, can you confirm? I pinged `test.xyc2690.xyz` and got a response, I was not able to before.

Could you login the webpage and take a look? Many thanks!
app.xyc2690.xyz
E:\GKE>opctl-windows-amd64.exe auth token
admin
22c3650f61866aa3f037a4ef280da7c8

**Comment by rushtehrani** [comment]
@xyc2690 tried logging in but was not able to. Can you confirm that you have set your `n1-standard-4` nodes to auto scale past 2 nodes?

```
--min-nodes 2 \
--max-nodes 5
```

**Comment by xyc2690** [comment]
> @xyc2690 tried logging in but was not able to. Can you confirm that you have set your `n1-standard-4` nodes to auto scale past 2 nodes?
> 
> ```
> --min-nodes 2 \
> --max-nodes 5
> ```

I comfirm that the configs are exactly the same as that in the tutorial.
Could you please try again? I can login successfully.
```
app.xyc2690.xyz
admin
22c3650f61866aa3f037a4ef280da7c8
```

**Comment by rushtehrani** [comment]
Looks like you already launched a new one and it's working. I just tried launching the one that failed and that worked as well. Can you verify that things are working now?

**Comment by xyc2690** [comment]
> Looks like you already launched a new one and it's working. I just tried launching the one that failed and that worked as well. Can you verify that things are working now?

 I my case I can not create a workspace. Can you create a workspace?
And when I check the po, I get follow info.
```
kubectl.exe describe po -n onepaneldemo jup-0
Events:
  Type     Reason                  Age                  From                     Message
  ----     ------                  ----                 ----                     -------
  Warning  FailedScheduling        112s (x2 over 114s)  default-scheduler        pod has unbound immediate PersistentVolumeClaims
  Normal   Scheduled               110s                 default-scheduler        Successfully assigned onepaneldemo/jup-0 to gke-onepanel-default-pool-6026022f-jfk2
  Normal   SuccessfulAttachVolume  104s                 attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-c2860543-e1ed-41e3-bf0e-402e9e7cdf5b"
  Normal   Started                 100s                 kubelet                  Started container istio-init
  Normal   Pulling                 100s                 kubelet                  Pulling image "docker.io/istio/proxyv2:1.7.3"
  Normal   Pulled                  100s                 kubelet                  Successfully pulled image "docker.io/istio/proxyv2:1.7.3"
  Normal   Created                 100s                 kubelet                  Created container istio-init
  Normal   Created                 99s                  kubelet                  Created container istio-proxy
  Normal   Pulling                 99s                  kubelet                  Pulling image "docker.io/istio/proxyv2:1.7.3"
  Normal   Pulled                  99s                  kubelet                  Successfully pulled image "docker.io/istio/proxyv2:1.7.3"
  Normal   Started                 98s                  kubelet                  Started container istio-proxy
  Normal   Pulling                 97s                  kubelet                  Pulling image "alpine:latest"
  Normal   Pulled                  95s                  kubelet                  Successfully pulled image "alpine:latest"
  Normal   Created                 95s                  kubelet                  Created container node-capturer
  Normal   Started                 94s                  kubelet                  Started container node-capturer
  Normal   Pulling                 94s                  kubelet                  Pulling image "onepanel/jupyterlab:1.0.1"
```

**Comment by rushtehrani** [comment]
Note that depending on your cloud provider, this could take 5-8 mins. It has to basically scale up a node if it doesn't exist and then pull the Docker images into it. I see that you just launched a workspace and you had launched two before.

**Comment by xyc2690** [comment]
> Note that depending on your cloud provider, this could take 5-8 mins. It has to basically scale up a node if it doesn't exist and then pull the Docker images into it. I see that you just launched a workspace and you had launched two before and I am able to access all 3 of them on my end.

I use firefox ,edge and IE browser, and I can not see the workspaces, is it a problem?

**Comment by rushtehrani** [comment]
> Many thanks, finally I can see the workspace!

Great! Happy to help.
